HLasse/TextDescriptives

- README.md
- docs/usingthepackage.rst
- textdescriptives/__init__.py
- textdescriptives/dataframe_extract.py
- textdescriptives/tests/test_extractor.py
> add extract_dict function

- requirements.txt
downgrade numpy requirement to numpy>=1.15.0
> change numpy requirement

- requirements.txt
- textdescriptives/tests/test_dependency_distance.py
- textdescriptives/tests/test_pos_stats.py
Fixes failing tests due to updated spacy models changing the extracted POS proportions slightly. Closes #29
> update: more wiggle room for pos tests

- .github/dependabot.yml
Added workflow to 'automagicallly' update dependencies.
> Added dependabot workflow

- .github/workflows/pytest-cov-comment.yml
1) Fixed error causing workflows to pass even though tests fail caused by the purest not raising an error due to the tee.
2) Fixed error causing cov-comment workflow to fail due on PRs
> Fixed error causing workflows to pass

- docs/dependencydistance.rst
> docs: docs for dependency distance formula

- NEWS.md
- textdescriptives/__init__.py
- textdescriptives/components/__init__.py
- textdescriptives/components/dependency_distance.py
- textdescriptives/components/descriptive_stats.py
- textdescriptives/components/pos_proportions.py
- textdescriptives/components/quality.py
- textdescriptives/components/readability.py
- textdescriptives/dataframe_extract.py
- textdescriptives/load_components.py
- textdescriptives/tests/test_dependency_distance.py
- textdescriptives/tests/test_descriptive_stats.py
- textdescriptives/tests/test_extractor.py
- textdescriptives/tests/test_load_components.py
- textdescriptives/tests/test_pos_proportions.py
- textdescriptives/tests/test_quality.py
- textdescriptives/tests/test_readability.py
> feat: Separate component loaders

- docs/coherence.rst
- docs/index.rst
- textdescriptives/components/__init__.py
- textdescriptives/components/coherence.py
- textdescriptives/tests/test_coherence.py
Was extremely simple to do, so had a go at it. Was unsure how best to set the attributes here - any thoughts and pointers are welcome. 
Fixes #50
> feat: add word embedding coherence/similarity

- .github/workflows/tests.yml
> ci: add token to cov comment

- docs/coherence.rst
> docs: fix typo in coherence.rst

- docs/tutorials/introductory_tutorial.ipynb
Made download of pipeline optional to avoid big download logs when creating the documentation (this also avoid downloading the model twice).
> doc: fix rendering of introductory tutorail

- .github/workflows/release.yml
This should fix the current error derived from the sem. release
> ci: Fix semantic release

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
> Add contributor guidelines

- paper/paper.md
- paper/paper_quarto.qmd
> Paper-add-ludvig

- .zenodo.json
- paper/paper.md
- paper/paper_quarto.qmd
Adds a .zenodo.json for correct metadata to zenodo. Minor paper formatting
> Fix-paper-and-zenodo

- docs/tutorials/filter_corpus_using_quality.ipynb
- docs/tutorials/introductory_tutorial.ipynb
- src/textdescriptives/components/coherence.py
- src/textdescriptives/components/quality.py
- tests/test_coherence.py
- tests/test_dependency_distance.py
- tests/test_extractors.py
- tests/test_quality.py
- Fixes cases where it fails on empty string for quality and coherence component
- Updated tests
Fixes #213
> fixed fail on empty string

- .github/workflows/tests.yml
- docs/tutorial.rst
- docs/tutorials/sklearn_integration.ipynb
- pyproject.toml
- src/textdescriptives/extractors.py
- src/textdescriptives/integrations/sklearn_featurizer.py
- src/textdescriptives/sklearn_featurizer.py
Adds a `sklearn.base.TransformerMixin` component for TextDescriptives that allows it to be easily used in a sklearn pipeline. Also adds simple tutorial showing how to use it. Discussed in #221
> feat: sklearn integration

- pyproject.toml
> Removed upper bound on robust libraries

- docs/tutorials/filter_corpus_using_quality.ipynb
Fixes #321. Simply skips the part of the tutorial relying on the DAGW dataset
> tutorials: quality tutorial failing due to DAGW not being available at the moment

- src/textdescriptives/components/quality.py
- tests/test_quality.py
> fix: `contains` and `symbols` not updated in `Quality`
